INSERT INTO utente (email,nome,cognome,password,tipo,emailAssociazione) VALUES
('caimarche@gmail.com','CAI MARCHE',NULL,'76jo98lk','a',NULL),
('dante.alighieri@gmail.com','Dante','Alighieri','da77yh','c','caimarche@gmail.com'),
('fai@gmail.com','FAI',NULL,'1234','a',NULL),
('francesca.gialli@gmail.com','Francesca','Gialli','pw427','c',NULL),
('lucia.verdi@gmail.com','Lucia','Verdi','pass123','t',NULL),
('luisa.spagnoli@gmail.com','Luisa','Spagnoli','pw4guu','c','fai@gmail.com'),
('maria.bianchi@gmail.com','Maria','Bianchi','rs5567','c','fai@gmail.com'),
('mario.rossi@gmail.com','Mario','Rossi','password','c','fai@gmail.com'),
('matteo.tarsi@gmail.com','Matteo','Tarsi','1mm28g','t',NULL),
('turismoLombardia@gmail.com','Turismo Lombardia',NULL,'TL78x*','a',NULL);

INSERT INTO toponimo VALUES 
("Italia","Italia"),
("Marche", "Italia"),
("Lombardia", "Italia"),
("Abruzzo", "Italia"),
("Trentino Alto Adige", "Italia"),
("Lazio", "Italia"),
("Campania", "Italia"),
("Sicilia", "Italia"),
("Umbria", "Italia"),
("Sardegna", "Italia"),
("Appennino Centrale", "Italia"),
("Fermo","Marche"),
("Ancona","Marche"),
("Ascoli Piceno","Marche"),
("Riviera Marchigiana","Marche"),
("Colline Marchigiane","Marche"),
("Milano","Lombardia"),
("Bergamo", "Lombardia"),
("Industria Lombarda", "Lombardia"),
("Napoli", "Campania"),
("Costiera Amalfitana", "Campania"),
("Cilento", "Campania"),
("Roma","Lazio"),
("Alpi", "Italia"),
("Catania", "Sicilia"),
("Palermo", "Sicilia"),
("Valle dei Templi", "Sicilia"),
("Isole Eolie", "Sicilia"),
("Pescara","Abruzzo"),
("Chieti", "Abruzzo"),
("Costa Abruzzese", "Abruzzo"),
("Appennino Abruzzeze", "Abruzzo"),
("Costa Adriatica", "Italia");

INSERT INTO esperienza (id,titolo,descrizione,data,postiDisponibili,postiMassimi,postiMinimi,prezzo,emailGuida,toponimo) VALUES
(1,'Passeggiata sulla riviera marchigiana','Una piacevole passeggiata nelle principali località balneari della costa marchigiana.','2022-04-16',13,15,2,20,NULL,'Riviera Marchigiana'),
(2,'Degustazione di vini nelle principali cantine abruzzesi','Percorso enogastronomico in più tappe nelle principali cantine abruzzesi.','2022-03-03',30,30,1,25,'dante.alighieri@gmail.com','Abruzzo'),
(3,'Escursione sulle principali montagne dell\'Appennino centrale','Escursione adatta ad alpinisti esperti, dove toccheremo le varie vette dell\'appennino centrale.','2022-03-16',14,10,5,20,'mario.rossi@gmail.com','Appennino Centrale'),
(4,'Aperitivo con tramonto sulla costiera amalfitana','Rilassati degustando un ottimo aperitivo e godendo del suggestiovo paesaggio della costiera Amalfitana.','2022-06-22',20,20,5,35,'mario.rossi@gmail.com','Costiera Amalfitana'),
(51349,'Passeggiata nella Valle dei Templi','Passeggiata tra le rovine delle antiche civiltÃ ','2022-05-05',8,10,2,32,'mario.rossi@gmail.com','Valle dei Templi');

INSERT INTO tag (nome) VALUES 
('Aperitivo'),
('Campagna'),
('Collina'),
('Cultura'),
('Manifattura'),
('Mare'),
('Montagna'),
('Musei'),
('Natura'),
('Panorama'),
('Tramonto'),
('Vino');

INSERT INTO tagdaapprovare (nome) VALUES ('Industria');

INSERT INTO esperienza_tag (Esperienzaid,Tag) VALUES
(4,'Aperitivo'),
(2,'Campagna'),
(1,'Collina'),
(2,'Collina'),
(3,'Collina'),
(51349,'Cultura'),
(1,'Mare'),
(4,'Mare'),
(3,'Montagna'),
(51349,'Musei'),
(1,'Natura'),
(3,'Natura'),
(4,'Tramonto'),
(2,'Vino');

INSERT INTO disponibilita (emailCicerone,data) VALUES 
('dante.alighieri@gmail.com','2022-04-05'),
('dante.alighieri@gmail.com','2022-04-06'),
('luisa.spagnoli@gmail.com','2022-04-17'),
('maria.bianchi@gmail.com','2022-03-05'),
('maria.bianchi@gmail.com','2022-03-06'),
('maria.bianchi@gmail.com','2022-03-30'),
('maria.bianchi@gmail.com','2022-05-28'),
('mario.rossi@gmail.com','2022-03-10'),
('mario.rossi@gmail.com','2022-03-11'),
('mario.rossi@gmail.com','2022-04-11'),
('mario.rossi@gmail.com','2022-04-17'),
('mario.rossi@gmail.com','2022-04-18'),
('mario.rossi@gmail.com','2022-04-19'),
('mario.rossi@gmail.com','2022-04-20'),
('mario.rossi@gmail.com','2022-05-05'),
('mario.rossi@gmail.com','2022-05-22'),
('mario.rossi@gmail.com','2022-06-11'),
('mario.rossi@gmail.com','2022-06-13'),
('mario.rossi@gmail.com','2022-06-23'),
('mario.rossi@gmail.com','2022-07-12'),
('mario.rossi@gmail.com','2022-08-18'),
('mario.rossi@gmail.com','2022-08-19');

INSERT INTO pagamento (id,importo,Utenteemail,Esperienzaid) VALUES
(1,60,'matteo.tarsi@gmail.com',1),
(2,100,'matteo.tarsi@gmail.com',3),
(3,210,'matteo.tarsi@gmail.com',4),
(382017,64,'lucia.verdi@gmail.com',51349);

INSERT INTO partecipante (id,email,Esperienzaid) VALUES 
(1,'mario.bianchi@libero.it',1),
(2,'luisa.giallini@gmail.com',1),
(3,'giuseppe.verdi@tiscali.it',3),
(4,'francesca.testa@gmail.com',3),
(5,'iginio.massari@gmail.com',3),
(6,'bruno.barbieri@gmail.com',3),
(7,'antonino.cannavacciolo@gmail.com',4),
(8,'giorgio.locatelli@gmail.com',4),
(9,'antonia.klugmann@gmail.com',4),
(10,'simone.scipioni@gmail.com',4),
(11,'terry.giacomelli@gmail.com',4),
(12,'matteo.tarsi@gmail.com',4),
(13,'matteo.tarsi@gmai.com',3),
(14,'matteo.tarsi@gmail.com',1),
(74697,'sergio.mattarella@gmail.com',51349),
(349886,'mattia2020@gmail.com',51349);

INSERT INTO tappa (nome,descrizione,indirizzo,Esperienzaid) VALUES
('Sirolo','tappa spiaggia Sirolo','Via Leopardi 13',1),
('Civitanova Marche','Spiaggia civitanovese','Lungomare Antonio Gramsci',1),
('San Benedetto Del Tronto','Lungomare della riviera delle palme','Lungomare Dante Alighieri',1),
('Cantina Masciarelli','Degustazione dei migliori vini della cantina','Via Leopoldo 15',2),
('Cantina Frentana','Assaggio delle nuove proposte','Via Medaglie D\'oro 22',2),
('Monte Vettore','Principale vetta marchigiana','Nessun indirizzo',3),
('Monte Sibilla','Tappa nella montagna più suggestiva dell\'Appennino','Nessun indirizzo',3),
('Beerstrot','Birra sulla spiaggia con degustazione di snack','Via Amalfi 33',4),
('Vino e co.','Degustazione di vini accompagnata da pesce locale','Via Amalfi 15',4),
('Pizzeria da Michele','Assaggio della vera pizza napoletana','Via Amalfi 10',4),
('Agrigento','Prima tappa. Ristoro nella parte moderna della cittÃ .','Agrigento AG',51349),
('Valle dei Templi','Passeggiata tra le meraviglie del passato delle civiltÃ  di queste terre.','Via dei Templi 22',51349);
